name: CI & CD for NestJS Project

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - package.json
      - package-lock.json
      - tsconfig.json
      - src/**
      - .github/workflows/**
      - global-bundle.pem.enc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_PLATFORMS: linux/arm64
  CACHE_TAG: buildcache

jobs:
  build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    environment: devops_aws
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      ECR_REPO: ${{ vars.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (binfmt)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.12.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Decrypt global-bundle.pem.enc
        run: |
          set -euo pipefail
          if [ ! -f global-bundle.pem.enc ]; then
            echo "global-bundle.pem.enc not found"
            exit 1
          fi
          openssl enc -aes-256-cbc -d -salt \
            -in global-bundle.pem.enc \
            -out global-bundle.pem \
            -pass pass:"${{ secrets.PASSPHRASE }}"
          sha256sum global-bundle.pem | cut -d' ' -f1

      - name: Build & Push (no cache to ensure fresh bundle)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          no-cache: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:latest
          cache-to: type=inline

      - name: Delete old untagged images in ECR
        run: |
          set -euo pipefail
          IMAGE_IDS=$(aws ecr list-images \
            --repository-name "${{ env.ECR_REPO }}" \
            --filter tagStatus=UNTAGGED \
            --query 'imageIds[*]' --output json)
          if [ "$IMAGE_IDS" != "[]" ]; then
            aws ecr batch-delete-image \
              --repository-name "${{ env.ECR_REPO }}" \
              --image-ids "$IMAGE_IDS"
          fi

  deploy:
    name: Deploy to EC2 via SSM
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: devops_aws
    permissions:
      contents: read
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      ECR_REPO: ${{ vars.ECR_REPOSITORY }}
      EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
      PUBLIC_IP: ${{ vars.PUBLIC_IP }}
      EXTERNAL_PORT: ${{ vars.EXTERNAL_PORT }}
      CONTAINER_NAME: back_results
      IMAGE_TAG: ${{ github.sha }}
      SSM_ENV_PARAM_NAME: ${{ vars.SSM_ENV_PARAM_NAME }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy container using SSM
        id: ssm
        shell: bash
        run: |
          set -euo pipefail

          SSM_NAME="${SSM_ENV_PARAM_NAME:-/miapp/dev/.env}"
          echo "Deploying ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG} to ${EC2_INSTANCE_ID}"
          echo "SSM parameter: ${SSM_NAME}"

          # Build the remote script safely (no special YAML chars)
          cat > remote_cmds.txt <<'EOF'
set -euo pipefail
aws ecr get-login-password --region __AWS_REGION__ | docker login --username AWS --password-stdin __ECR_REGISTRY__
docker pull --quiet __ECR_REGISTRY__/__ECR_REPO__:__IMAGE_TAG__
docker stop __CONTAINER_NAME__ || true
docker rm __CONTAINER_NAME__ || true
aws ssm get-parameter --name __SSM_NAME__ --with-decryption --query Parameter.Value --output text > .env
sed -i 's/\r$//' .env
echo "ENV bytes=$(wc -c < .env) lines=$(wc -l < .env)"
docker run -d --name __CONTAINER_NAME__ -p __EXTERNAL_PORT__:3000 --env-file .env -e NODE_EXTRA_CA_CERTS=/app/global-bundle.pem --restart unless-stopped __ECR_REGISTRY__/__ECR_REPO__:__IMAGE_TAG__
sleep 2
docker exec __CONTAINER_NAME__ /bin/sh -lc 'set -e; [ -f /app/global-bundle.pem ] && echo "bundle OK" && ls -l /app/global-bundle.pem && sha256sum /app/global-bundle.pem | cut -c1-16 || (echo "bundle MISSING"; exit 1)'
docker exec __CONTAINER_NAME__ /bin/sh -lc 'env | grep -E "^(MONGODB_URI|MONGODB_USERNAME|MONGODB_PASSWORD|NODE_EXTRA_CA_CERTS)=" | sed "s/=.*/=[REDACTED]/"'
docker inspect --format="Name={{.Name}} Image={{.Config.Image}} Cmd={{.Config.Cmd}} Entrypoint={{.Config.Entrypoint}}" __CONTAINER_NAME__ || true
docker image inspect __ECR_REGISTRY__/__ECR_REPO__:__IMAGE_TAG__ --format 'RepoDigests: {{json .RepoDigests}} Cmd: {{json .Config.Cmd}} Entrypoint: {{json .Config.Entrypoint}}' || true
shred -u .env || rm -f .env
docker image prune -f
EOF

          # Replace placeholders with env values
          sed -i \
            -e "s#__AWS_REGION__#${AWS_REGION}#g" \
            -e "s#__ECR_REGISTRY__#${ECR_REGISTRY}#g" \
            -e "s#__ECR_REPO__#${ECR_REPO}#g" \
            -e "s#__IMAGE_TAG__#${IMAGE_TAG}#g" \
            -e "s#__CONTAINER_NAME__#${CONTAINER_NAME}#g" \
            -e "s#__EXTERNAL_PORT__#${EXTERNAL_PORT}#g" \
            -e "s#__SSM_NAME__#${SSM_NAME}#g" \
            remote_cmds.txt

          # Convert lines to JSON array for SSM
          CMDS_JSON=$(jq -R -s -c 'split("\n") | map(select(length>0))' < remote_cmds.txt)

          CMD_ID=$(aws ssm send-command \
            --instance-ids "${EC2_INSTANCE_ID}" \
            --document-name "AWS-RunShellScript" \
            --comment "GitHub Actions deploy" \
            --parameters "commands=${CMDS_JSON}" \
            --query "Command.CommandId" --output text)

          echo "SSM CommandId = ${CMD_ID}"
          aws ssm wait command-executed --command-id "${CMD_ID}" --instance-id "${EC2_INSTANCE_ID}"

          aws ssm get-command-invocation \
            --command-id "${CMD_ID}" \
            --instance-id "${EC2_INSTANCE_ID}" \
            --query "{Stdout:StandardOutputContent, Stderr:StandardErrorContent, Status:Status}" \
            --output text | sed 's/\\n/\n/g'

          STATUS=$(aws ssm get-command-invocation \
            --command-id "${CMD_ID}" \
            --instance-id "${EC2_INSTANCE_ID}" \
            --query Status --output text)
          if [ "${STATUS}" != "Success" ]; then
            echo "Remote script failed"
            exit 1
          fi

      - name: Health check loop
        shell: bash
        run: |
          set -euo pipefail
          echo "Testing http://${PUBLIC_IP}:${EXTERNAL_PORT}/"
          for i in {1..24}; do
            http_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://${PUBLIC_IP}:${EXTERNAL_PORT}/") || true
            if [ "${http_code:-}" = "200" ]; then
              echo "Service OK (${http_code})"
              exit 0
            fi
            echo "Attempt $i/24 — code=${http_code:-timeout}"
            sleep 5
          done

          echo "Health-check failed, dumping container logs"
          aws ssm send-command \
            --instance-ids "$EC2_INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters commands="docker logs --tail 200 $CONTAINER_NAME" \
            --query "Command.CommandId" --output text \
          | xargs -I{} aws ssm wait command-executed --command-id {} --instance-id "$EC2_INSTANCE_ID"
          exit 1
